const STAGES=[
{n:'Foundations',l:[
{t:'Setup & first run',r:"Python runs plain text files. Install Python 3.12+ from python.org, then test it in your terminal.\n\n~~~\npython3 --version\npython3 hello.py\n~~~\n\nType `python3` alone to open the REPL, a scratchpad for one-line experiments. Leave it with `exit()`.",ref:'Automate the Boring Stuff, ch. 0–1',k:['Install Python and run python3 --version','Create hello.py that prints your name, then run it','Open the REPL, compute 2**10, then exit()'],q:['How do you run hello.py?',['python3 hello.py','open hello.py','python hello'],0]},
{t:'Variables & types',r:"A variable is a name pointing at a value. Python infers the type.\n\n~~~\nage = 30\nname = 'Sam'\nprice = 9.99\nready = True\nprint(type(age))\n~~~\n\nCore types: `int`, `float`, `str`, `bool`. Names use snake_case.",ref:'Automate the Boring Stuff, ch. 1',k:['Create one variable of each type and print its type()','Swap two variables in one line: a, b = b, a'],q:['type(3.0) is…',['int','float','str'],1]},
{t:'Strings & input',r:"Strings hold text. f-strings drop values in cleanly, and `input()` reads from the keyboard.\n\n~~~\nname = input('Name? ')\nprint(f'Hi {name.title()}! {len(name)} letters')\nprint(name[0], name[-1], name[::-1])\n~~~\n\n`input()` always returns a string. Convert with `int()`.",ref:'Automate the Boring Stuff, ch. 1 & 6',k:['Ask for name and age, then print a sentence with an f-string','Try slices: name[1:3] and name[::-1]'],q:['What does input() return?',['an int','a str','depends'],1]}]},
{n:'Control flow',l:[
{t:'Conditions',r:"Code branches with `if`, `elif`, `else`. Four-space indentation defines the block.\n\n~~~\nif score >= 90:\n    grade = 'A'\nelif score >= 80:\n    grade = 'B'\nelse:\n    grade = 'C'\n~~~\n\nCompare with `==`, `!=`, `<`, `>=`. Combine with `and`, `or`, `not`.",ref:'Automate the Boring Stuff, ch. 2',k:['Turn a 0–100 score into a letter grade','Check whether a year is a leap year'],q:['Which operator tests equality?',['=','==','=>'],1]},
{t:'Loops',r:"`for` repeats over a sequence. `while` repeats until its condition fails.\n\n~~~\nfor i in range(3):\n    print(i)\nn = 0\nwhile n < 3:\n    n += 1\n~~~\n\n`break` exits the loop. `continue` skips to the next pass.",ref:'Automate the Boring Stuff, ch. 2',k:['Print a multiplication table for any number','Solve FizzBuzz (1–100) without looking it up','Build a number-guessing game with random.randint and while'],q:['range(3) yields…',['1, 2, 3','0, 1, 2','0, 1, 2, 3'],1]}]},
{n:'Data',l:[
{t:'Lists',r:"A list is an ordered, changeable collection.\n\n~~~\nnums = [3, 1, 2]\nnums.append(5)\nnums.sort()\nprint(nums[0], nums[-1], nums[1:3], len(nums))\n~~~\n\nLoop with `for n in nums:`. Test membership with `in`.",ref:'Automate the Boring Stuff, ch. 4',k:['Find the max and average of a list without max()','Remove duplicates from a list, keeping order'],q:['nums[-1] is the…',['first item','last item','error'],1]},
{t:'Dicts & sets',r:"A dict maps keys to values with fast lookup. A set stores unique items.\n\n~~~\nage = {'ana': 31, 'bo': 27}\nage['cy'] = 40\nfor name, a in age.items():\n    print(name, a)\nunique = set([1, 1, 2])\n~~~\n\nTuples like `(1, 2)` are lists you can't change.",ref:'Automate the Boring Stuff, ch. 5',k:['Count how often each word appears in a sentence','Use a set to find words shared by two sentences'],q:['Dict keys are used to…',['look up values','sort items','loop faster'],0]},
{t:'Comprehensions',r:"A comprehension builds a collection in one readable line.\n\n~~~\nsquares = [n*n for n in range(10)]\nevens = [n for n in nums if n % 2 == 0]\nlengths = {w: len(w) for w in words}\n~~~\n\nIf it gets long, use a normal loop. Clarity wins.",ref:'Python Tutorial, section 5.1.3',k:['Rewrite two earlier loops as comprehensions','Sort strings by length: sorted(words, key=len)'],q:['[n for n in range(4)] gives…',['[1,2,3,4]','[0,1,2,3]','(0,1,2,3)'],1]}]},
{n:'Functions & errors',l:[
{t:'Functions',r:"Functions package reusable logic.\n\n~~~\ndef greet(name, punct='!'):\n    return f'Hi {name}{punct}'\n\ndef total(*nums, **opts):\n    return sum(nums)\n~~~\n\nNo `return` means the function returns `None`. Keep functions small and single-purpose.",ref:'Automate the Boring Stuff, ch. 3',k:['Write is_prime(n) and list the primes under 100','Write a function with a default argument and call it three ways'],q:['A function with no return gives…',['0','None','error'],1]},
{t:'Errors & debugging',r:"Errors are information. Read a traceback from the bottom up: the last line says what, the lines above say where.\n\n~~~\ntry:\n    n = int(input('Number: '))\nexcept ValueError:\n    print('Not a number')\nelse:\n    print(n * 2)\n~~~\n\nCatch specific errors, never a bare `except:`. Raise your own with `raise ValueError('msg')`.",ref:'Automate the Boring Stuff, ch. 11',k:['Build a calculator that survives bad input and divide-by-zero','Cause 3 different errors on purpose and read each traceback'],q:['A traceback is best read…',['top down','bottom up','never'],1]}]},
{n:'Files & tooling',l:[
{t:'Files & JSON',r:"Use `with` so files close themselves.\n\n~~~\nfrom pathlib import Path\nimport json\nPath('notes.txt').write_text('hi')\nwith open('data.json', 'w') as f:\n    json.dump({'a': 1}, f)\ndata = json.loads(Path('data.json').read_text())\n~~~",ref:'Automate the Boring Stuff, ch. 9–10',k:['Save a list of dicts to JSON, then load it back','Count the lines in every .py file in a folder'],q:['Why use `with open(...)`?',['it is faster','it closes the file for you','it is required'],1]},
{t:'Modules, venv & git',r:"Split code into files and `import` between them. Isolate each project's packages in a virtual environment.\n\n~~~\npython3 -m venv .venv\nsource .venv/bin/activate\npip install requests\ngit init\ngit add .\ngit commit -m 'start'\n~~~\n\nCommit small and often. Push to GitHub: it becomes your portfolio.",ref:'Python Tutorial, ch. 6 & 12',k:['Create a project folder with a venv and install requests','Split a script into two files and import between them','Create a GitHub repo and push your work'],q:['Why use a venv?',['per-project packages','faster Python','git needs it'],0]}]},
{n:'Object-oriented Python',l:[
{t:'Classes',r:"A class bundles data and behavior.\n\n~~~\nclass Account:\n    def __init__(self, owner, bal=0):\n        self.owner, self.bal = owner, bal\n    def deposit(self, x):\n        self.bal += x\n    def __repr__(self):\n        return f'Account({self.owner}, {self.bal})'\n~~~\n\n`self` is the instance a method runs on.",ref:'Python Tutorial, ch. 9',k:['Build a BankAccount with deposit/withdraw that blocks overdrafts','Print an instance and write a useful __repr__'],q:['__init__ runs…',['when an object is created','on import','on delete'],0]},
{t:'Inheritance & dataclasses',r:"Inherit to reuse behavior. `dataclass` removes boilerplate.\n\n~~~\nfrom dataclasses import dataclass\n\n@dataclass\nclass Pt:\n    x: int\n    y: int\n\nclass Animal:\n    def speak(self): return '...'\nclass Dog(Animal):\n    def speak(self): return 'Woof'\n~~~\n\nPrefer composition (objects holding objects) over deep inheritance.",ref:'Python docs: dataclasses',k:['Model Shape with Circle and Rect subclasses, each with area()','Rewrite one earlier class as a dataclass'],q:['@dataclass mainly saves you…',['memory','boilerplate','runtime errors'],1]}]},
{n:'Pro Python',l:[
{t:'Generators & decorators',r:"`yield` produces values lazily. A decorator wraps a function with extra behavior.\n\n~~~\nimport time\n\ndef count(n):\n    for i in range(n):\n        yield i\n\ndef timed(fn):\n    def wrap(*a, **k):\n        t = time.time()\n        r = fn(*a, **k)\n        print(time.time() - t)\n        return r\n    return wrap\n~~~",ref:'Fluent Python, ch. 17 & 9',k:['Write a Fibonacci generator and take the first 20 values','Write a @timed decorator and apply it to a slow function'],q:['yield turns a function into…',['a one-time return','a generator','an infinite loop'],1]},
{t:'Types & testing',r:"Type hints document intent. pytest proves your code works.\n\n~~~\ndef add(a: int, b: int) -> int:\n    return a + b\n\n# test_add.py\ndef test_add():\n    assert add(2, 3) == 5\n~~~\n\nInstall with `pip install pytest`, then run `pytest`. Write the test first when you can.",ref:'pytest docs: Get started',k:['Add type hints to three old functions','Write 5 pytest tests for is_prime, including edge cases'],q:['pytest discovers tests named…',['test_*','check_*','*_spec'],0]}]},
{n:'Real-world tools',l:[
{t:'Talking to the web (APIs)',s:"An API is like a waiter. You ask for something in a special way. The waiter runs to a kitchen on the internet and brings back an answer. The answer is usually JSON, which looks just like a Python dict.",c:[['import requests','Borrow a tool that talks to websites. Install it first with pip install requests.'],["r = requests.get('https://api.github.com/zen')",'Ask the website a question. r is the answer that comes back.'],['print(r.status_code)','A number that tells how it went. 200 means all good. 404 means not found.'],['print(r.text)','The words the website sent back.'],['data = r.json()','If the answer is JSON, turn it into a Python dict. Now you can use data like any dict.']],ref:'requests docs: Quickstart',k:['Install requests inside your venv','Call the GitHub zen API and print the text','Break the web address on purpose and read the 404'],q:['Status code 200 means…',['all good','not found','crashed'],0]},
{t:'Databases with SQLite',s:"A database is a very neat notebook that never forgets and finds things fast. SQLite is a small one that lives in one file. Python already has it built in.",c:[['import sqlite3','Borrow the built-in database tool.'],["db = sqlite3.connect('jarvis.db')",'Open the notebook file. If it is missing, Python makes it.'],["db.execute('CREATE TABLE IF NOT EXISTS notes (text TEXT)')",'Make a page with one column named text. IF NOT EXISTS stops an error on the second run.'],["db.execute('INSERT INTO notes VALUES (?)', ('buy milk',))",'Write one row. The ? is a safe slot for your value. Never glue user text into SQL yourself, because that is how hackers break in.'],['db.commit()','Save your changes.'],["print(db.execute('SELECT * FROM notes').fetchall())",'Read every row back as a list.']],ref:'Python docs: sqlite3',k:['Make a notes table and add 3 notes','Print them all back','Add a function that deletes a note by its text'],q:['The ? in SQL…',['safely holds your value','asks a question','does nothing'],0]}]},
{n:'Projects',l:[
{t:'Project: CLI to-do app',r:"Time to build. Make a to-do manager you run from the terminal: `python3 todo.py add 'buy milk'`. Use `argparse`, JSON storage, small functions, and tests.\n\nBuild in this order: storage, commands, CLI parsing, tests, README. Finish it, then push it to GitHub.",ref:'Python docs: argparse tutorial',k:['Implement add, list, done and delete','Persist to todo.json and handle a missing file','Add 5 tests and a README with usage'],q:['Which build order works best?',['storage, commands, then CLI','CLI first, guess the rest','everything at once'],0]},
{t:'Capstone: web API',r:"Ship a small web API. Expose your to-do logic over HTTP with FastAPI, add tests, and deploy it.\n\n~~~\nfrom fastapi import FastAPI\napp = FastAPI()\n\n@app.get('/todos')\ndef todos():\n    return []\n~~~\n\nNext up: SQL with SQLite, async, algorithms and system design. You now have the base to learn any of them on the job.",ref:'FastAPI docs: Tutorial',k:['Run the server with uvicorn and hit it with curl','Add create, list and delete endpoints with tests','Deploy it and put the link in your README'],q:['FastAPI is used to build…',['web APIs','desktop GUIs','games'],0]}]},
{n:'Build Jarvis (final project)',l:[
{t:'Jarvis 1: the brain loop',s:"Jarvis is a loop that listens, thinks and answers. Today it listens to your typing. Later it will hear your voice.",c:[['from datetime import datetime','Borrow the clock tool.'],['def think(text):','A machine that takes what you said and hands back an answer.'],["    if 'time' in text:",'If the word time is anywhere in what you said...'],["        return datetime.now().strftime('%H:%M')",'...answer with the clock time.'],["    return 'Say that again?'",'If nothing matched, say this. Always have a fallback.'],['while True:','Loop forever.'],["    print(think(input('You: ').lower()))",'Ask you, make it lowercase so Time and time match, think, then print the answer.']],ref:'Automate the Boring Stuff, ch. 2–3',k:['Put this in jarvis.py and run it','Add a reply for the word hello','Make the word quit stop the loop using break'],q:['Why use .lower()?',['so Time and time match','to shout','it is required'],0]},
{t:'Jarvis 2: skills',s:"A long if-else list gets messy. Better: a skill book, which is a dictionary. The key is a word to listen for. The value is the machine to run.",c:[['def tell_time():','Skill one: a small machine.'],["    return datetime.now().strftime('%H:%M')",'It hands back the time.'],['def open_wiki():','Skill two.'],["    webbrowser.open('https://wikipedia.org')",'Opens a website. Needs import webbrowser, which is built in.'],["    return 'Opening Wikipedia.'",'Hand back words so Jarvis can say them.'],["SKILLS = {'time': tell_time, 'wiki': open_wiki}",'The skill book. A word on the left, a machine on the right. No brackets after the names, because we are not running them yet.'],['for word, skill in SKILLS.items():','Go through the skill book one entry at a time.'],['    if word in text: return skill()','If you said the word, run that machine now and hand back its answer.']],ref:'Python docs: webbrowser',k:['Add 3 more skills: a joke, a dice roll, a calculator','Add a skill that saves a note to notes.txt','Print a list of what Jarvis can do when you say help'],q:['Why no brackets in the skill book?',['we run them later','it is a typo','brackets are banned'],0]},
{t:'Jarvis 3: voice',s:"Give Jarvis a mouth and ears. pyttsx3 speaks out loud. SpeechRecognition turns microphone sound into text. Careful: the free recognizer sends your audio to Google, so never say private things. Jarvis only listens when your code says so.",h:"Install in your terminal: `pip install pyttsx3 SpeechRecognition pyaudio`. If pyaudio fails on Mac, run `brew install portaudio` first. If it fails on Windows, try `pip install pipwin` then `pipwin install pyaudio`. Allow microphone access when your computer asks.",c:[['import pyttsx3','Borrow the speaking tool.'],['voice = pyttsx3.init()','Wake up the voice.'],["voice.say('Hello, I am Jarvis')",'Line up a sentence.'],['voice.runAndWait()','Speak it now and wait until it is done.'],['import speech_recognition as sr','Borrow the listening tool.'],['r = sr.Recognizer()','Make the ear.'],['with sr.Microphone() as mic:','Open the microphone for the next line only. It closes after.'],['    audio = r.listen(mic)','Listen until you stop talking.'],['text = r.recognize_google(audio)','Turn the sound into words. This sends the audio to Google.']],ref:'pyttsx3 and SpeechRecognition docs',k:['Make Jarvis say hello out loud','Make Jarvis repeat what you say','Wrap the listening in try/except for when it hears nothing'],q:['Where does the free recognizer send audio?',['to Google','nowhere','your fridge'],0]},
{t:'Jarvis 4: an AI brain',s:"Now Jarvis gets a real brain: a large language model, reached through an API, like the waiter lesson. You need an API key. A key is a secret password that is also your credit card. Never put it in your code. Never push it to GitHub. Set a spending limit in the provider's dashboard.",h:"Get a key from console.anthropic.com. Mac or Linux: run `export ANTHROPIC_API_KEY=your-key` in the terminal. Windows PowerShell: run `$env:ANTHROPIC_API_KEY='your-key'`. Make a file named .gitignore and write .env on its own line, so git never uploads secrets. If a key ever leaks, delete it in the dashboard at once. Any provider works the same way. You only swap the tool and the model name.",c:[['pip install anthropic','Install the official tool, in the terminal.'],['import anthropic','Borrow it.'],['client = anthropic.Anthropic()','Make a phone that can call the AI. It finds your key by itself.'],["reply = client.messages.create(model='claude-haiku-4-5-20251001', max_tokens=300, messages=[{'role': 'user', 'content': text}])",'Ask the AI. model picks the brain, max_tokens limits how long it can talk, messages is the chat so far.'],['answer = reply.content[0].text','The answer comes in pieces. Piece 0 holds the words.']],ref:'Anthropic docs: Messages API',k:['Set your key and a spending limit','Make Jarvis answer any question with the AI','Use the AI only when no skill matched, so it costs less'],q:['Where should an API key live?',['in your terminal settings','in your code','on GitHub'],0]},
{t:'Jarvis 5: memory and safety',s:"A brain that forgets every turn is annoying. Memory is just a list of everything said, sent along each time. And the golden rule: Jarvis may suggest an action, but you press yes.",c:[['history = []','An empty notebook for the chat.'],["history.append({'role': 'user', 'content': text})",'Write down what you said.'],['reply = client.messages.create(model=MODEL, max_tokens=300, messages=history)','Send the whole notebook, so the AI remembers. MODEL is the model name you saved in a variable.'],['answer = reply.content[0].text','Pull out the words.'],["history.append({'role': 'assistant', 'content': answer})",'Write down what Jarvis said too.'],["if input('Run it? y/n ') == 'y':",'Before anything risky, like deleting files or running commands, ask first. Never skip this.']],ref:'Anthropic docs: Messages API',k:['Give Jarvis memory and test it by asking about your name','Save history to JSON so it survives restarts','Add a yes/no check before any skill that changes files'],q:['Why ask before risky actions?',['AI can be wrong','it is slower','it looks cool'],0]},
{t:'Jarvis 6: ship it',s:"Finish like a pro. Put Jarvis in a git repo, write a README, test the skills, and share it. Never include your key. You are now a Python developer.",c:[['pytest','Run your tests, for example one that checks tell_time returns text.'],['git add .','Pick all the files.'],["git commit -m 'Jarvis v1'",'Save a snapshot with a note.'],['git push','Send it to GitHub.']],ref:'Pro Git book, ch. 2',k:['Write 3 tests for your skills','Write a README with a demo and setup steps','Push to GitHub and check no key is in the files'],q:['Before git push, check…',['no secret keys inside','the weather','your typing speed'],0]}]}
];
